FROM ubuntu:18.04
ENV DEBIAN_FRONTEND noninteractive
copy ./galera.list /etc/apt/sources.list.d/
RUN apt-get update; \
    apt-get install -y software-properties-common; \
    apt-key adv --keyserver keyserver.ubuntu.com --recv BC19DDBA; \
    RUN add-apt-repository 'deb https://releases.galeracluster.com/ubuntu trusty main'; \
    apt-get update; \
    apt-get install -y galera-3 galera-arbitrator-3 mysql-wsrep-5.6 rsync lsof;

COPY my.cnf /etc/mysql/my.cnf
ENTRYPOINT ["mysqld"]