FROM ubuntu:18.04

ENV VERSION 20170605
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install -y ca-certificates  software-properties-common && \
    apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 BC19DDBA
COPY ./galera.list /etc/apt/sources.list.d/
RUN apt-get update && \
    apt-get install -y galera-3 galera-arbitrator-3 mysql-wsrep-5.7 rsync lsof && \
    apt-get clean
RUN rm -r /var/lib/mysql


COPY my.cnf /etc/mysql/my.cnf
COPY entrypoint.sh /entrypoint.sh
RUN chmod 700 /entrypoint.sh
EXPOSE 3306/tcp
ENTRYPOINT ["/entrypoint.sh"]

LABEL mysql_verion=5.7
