name: alpine
on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    paths:
      - 'alpine/**'
jobs:
  multi:
    runs-on: [self-hosted]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Context for Buildx
      id: buildx-context
      run: |
        docker context create builders
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        endpoint: builders
    - name: Build and push
      run: |
        set -eux;
        for file_path in $(find alpine -name Dockerfile | sort -r | head -n 4);
        do
          /usr/bin/docker buildx prune -a -f
          /usr/bin/docker buildx build --push --no-cache \
            --platform linux/amd64,linux/arm64 \
            --file ${file_path} \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/$(dirname $file_path | sed 's / : g') \
            ${file_path%/*}
        done
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 3
