# This is a basic workflow to help you get started with Actions

name: docker build & push kube-controller-manager

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - "featrue-*"
      - "release-*"
    paths:
      - kubernetes/kube-controller-manager.Dockerfile
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./kubernetes/kube-controller-manager.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: |
            yishuida/kube-controller-manager:v1.19.4
            yishuida/kube-controller-manager:latest
